version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/run
    container_name: python-backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8642:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf

    container_name: nginx-frontend
    depends_on:
      - backend
