version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/run    # This mounts your local code to container
    container_name: python-backend

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/share/nginx/html    # Frontend live updates
    container_name: nginx-frontend
    depends_on:
      - backend