version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/run
    container_name: python-backend

  frontend:
    image: nginx:alpine
    ports:
      - "8642:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_conf/mime.types:/etc/nginx/mime.types:ro
    container_name: nginx-frontend
    depends_on:
      - backend
